import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@chat/ui";
import { useState } from "react";
export default function Sidebar({ profile, conversations, activeConversationId, onSelectConversation, onCreateDirect, onAvatarChange }) {
    const initials = profile?.displayName?.[0]?.toUpperCase() ?? "?";
    const [avatarInput, setAvatarInput] = useState(profile?.avatarUrl ?? "");
    return (_jsxs("div", { className: "sidebar", children: [_jsxs("div", { className: "sidebar-user", children: [_jsx("div", { className: "avatar", style: {
                            background: profile?.avatarColor ?? undefined
                        }, children: profile?.avatarUrl ? (_jsx("img", { src: profile.avatarUrl, alt: profile.displayName })) : (initials) }), _jsxs("div", { children: [_jsx("p", { className: "username", children: profile?.displayName ?? "游客" }), _jsx("p", { className: "user-status", children: profile ? `状态：${profile.status}` : "公共聊天室 · 游客模式" })] })] }), _jsx(Button, { variant: "secondary", onClick: onCreateDirect, disabled: !profile, children: "\u65B0\u5EFA\u79C1\u804A" }), profile && (_jsxs("div", { className: "sidebar-section", children: [_jsx("div", { className: "section-header", children: _jsx("p", { children: "\u5934\u50CF\u94FE\u63A5" }) }), _jsxs("div", { className: "avatar-form", children: [_jsx("input", { value: avatarInput, onChange: (e) => setAvatarInput(e.target.value), placeholder: "\u8F93\u5165\u5934\u50CF URL" }), _jsx(Button, { variant: "secondary", onClick: () => onAvatarChange(avatarInput), children: "\u4FDD\u5B58" })] })] })), _jsxs("div", { className: "sidebar-section", children: [_jsxs("div", { className: "section-header", children: [_jsx("p", { children: "\u6211\u7684\u4F1A\u8BDD" }), _jsx("span", { children: conversations.length })] }), _jsx("ul", { className: "conversation-list", children: conversations.map((conversation) => (_jsx("li", { className: conversation.id === activeConversationId ? "active" : "", children: _jsxs("button", { onClick: () => onSelectConversation(conversation.id), children: [_jsx("span", { className: "conversation-title", children: conversation.title }), _jsx("span", { className: "conversation-type", children: conversation.type === "direct" ? "私聊" : "公共" }), conversation.lastMessageAt && (_jsx("span", { className: "conversation-time", children: new Date(conversation.lastMessageAt).toLocaleString() }))] }) }, conversation.id))) })] })] }));
}
